version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: brfit
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
      - goos: windows
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: indigo-net
    name: Brf.it

brews:
  - name: brfit
    repository:
      owner: indigo-net
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/indigo-net/Brf.it
    description: "AI 코딩 어시스턴트를 위한 코드 브리핑 도구"
    license: MIT
    install: |
      bin.install "brfit"
    test: |
      system "#{bin}/brfit", "--version"
