version: 2

before:
  hooks:
    - go mod tidy

builds:
  # Linux amd64
  - id: linux-amd64
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
      - CC=zig-cc-x86_64-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -linkmode external
      - -extldflags '-static'

  # Linux arm64
  - id: linux-arm64
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
      - CC=zig-cc-aarch64-linux-gnu
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -linkmode external
      - -extldflags '-static'

  # macOS amd64
  - id: darwin-amd64
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
      - CC=zig-cc-x86_64-macos
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  # macOS arm64
  - id: darwin-arm64
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
      - CC=zig-cc-aarch64-macos
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  # Windows amd64
  - id: windows-amd64
    main: ./cmd/brfit
    binary: brfit
    env:
      - CGO_ENABLED=1
      - CC=zig-cc-x86_64-windows-gnu
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: indigo-net
    name: Brf.it
